# NumPy Functions :

In [1]:
import numpy as np

# Arange()

In [2]:
# np.arange(start, end, steps)
ar_1d=np.arange(1,13)
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
even_ar=np.arange(2,13,2)
print(even_ar)

[ 2  4  6  8 10 12]


# Linspace()

In [4]:
# np.linspace(start, end, value)
np.linspace(1,6,5)

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

# reshape()

In [5]:
# Convert into 1d to multidimensional
ar_2d=ar_1d.reshape(3,4)
print(ar_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
ar_3d=ar_1d.reshape(2,3,2)
print(ar_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [7]:
ar=np.arange(1,15).reshape(2,7)
print(ar)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


# ravel()

In [8]:
# Convert into multidimensional to 1d
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
ar_3d.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten()

In [10]:
# Convert into multidimensional to 1d
ar_3d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# transpose()

In [12]:
# convert into row to colume or convert into colume to row
ar.transpose()

array([[ 1,  8],
       [ 2,  9],
       [ 3, 10],
       [ 4, 11],
       [ 5, 12],
       [ 6, 13],
       [ 7, 14]])

In [15]:
ar_3d.T

array([[[ 1,  7],
        [ 3,  9],
        [ 5, 11]],

       [[ 2,  8],
        [ 4, 10],
        [ 6, 12]]])

In [19]:
np.transpose()

AttributeError: module 'numpy' has no attribute 'T'