In [1]:
import numpy as np

In [2]:
mx_1s=np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [3]:
mx_1s.size

9

In [4]:
mx_1s=np.ones(5)
print(mx_1s)

[1. 1. 1. 1. 1.]


In [5]:
mx_1s.size

5

In [6]:
mx_1s.dtype

dtype('float64')

In [7]:
mx_1s=np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
mx_1s=np.ones((3,4),dtype=int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [9]:
mx_1s=np.ones((3,4),dtype=bool)
print(mx_1s)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [10]:
mx_0s=np.zeros((5,4))
print(mx_0s)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
mx_0s=np.zeros((5,4),dtype=int)
print(mx_0s)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [12]:
mx_0s=np.zeros((5,4),dtype=bool)
print(mx_0s)

[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]


In [13]:
mx_0s=np.zeros((5,4),dtype=str)
print(mx_0s)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [14]:
mx_em=np.empty((4,4))
print(mx_em)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 7.56595733e-307]
 [8.34441742e-308 1.78022342e-306 6.23058028e-307 9.79107872e-307]
 [6.89807188e-307 7.56594375e-307 6.23060065e-307 1.78021527e-306]
 [8.34454050e-308 1.11261027e-306 1.15706896e-306 1.33512173e-306]]
